<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

function book_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
    switch ($entity->bundle()) {
        case 'book':
            $bookHelper = \Drupal::service('book.BookHelper');
            $title = $bookHelper->getTitle($entity);
            $build['title'][0]['#context']['value'] = $title;
            break;
    }
}

/**
 * Implements HOOK_node_access()
 *
 * @param EntityInterface $entity
 * @param AccountInterface $account
 * @return void
 */
function book_node_access(EntityInterface $entity, $operation, AccountInterface $account) {
    switch ($entity->bundle()) {
        case 'book':
            $roles = $account->getRoles();
            switch ($operation) {
                case 'view':
                    $bookHelper = \Drupal::service('book.BookHelper');
                    $isYearOld = $bookHelper->is1yearOld($entity);
                    if ($isYearOld && in_array('full_editor', $roles)) {
                        return AccessResult::forbidden();
                    }
                    break;
            }
            break;
    }
    return AccessResult::neutral();
}