<?php

use Drupal\Core\Access\AccessResult;
use Drupal\Core\Access\AccessResultInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_node_view().
 */
function book_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, string $view_mode): void {
  if ($entity->bundle() !== 'book') {
    return;
  }

  /** @var \Drupal\book\services\BookHelper $bookHelper */
  $bookHelper = \Drupal::service('book.BookHelper');
  $build['title'][0]['#context']['value'] = $bookHelper->getTitle($entity);
}

/**
 * Implements hook_node_access().
 *
 * Prevents full_editor roles from viewing books older than one year.
 */
function book_node_access(NodeInterface $entity, string $operation, AccountInterface $account): AccessResultInterface {
  if ($entity->bundle() !== 'book' || $operation !== 'view') {
    return AccessResult::neutral();
  }

  /** @var \Drupal\book\services\BookHelper $bookHelper */
  $bookHelper = \Drupal::service('book.BookHelper');

  if ($bookHelper->is1yearOld($entity) && in_array('full_editor', $account->getRoles(), TRUE)) {
    return AccessResult::forbidden()->addCacheableDependency($entity);
  }

  return AccessResult::neutral();
}
